apiVersion: v1
kind: Pod
metadata:
  name: demo-golang
spec:
  containers:
  - image: gcr.io/real-estate-186513/rs-catalog-api:v1
    command: ["rs-catalog-api"]
    name: alpine-linux
    imagePullPolicy: IfNotPresent